### ISSUE TITLE
Fix endianness issue.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openpower-host-ipmi-oem#5]
This was introduced with #4: 

```
short *recid  =  (short*) &reqptr->selrecordls;
short *offset =  (short*) &reqptr->offsetls; 
```

This is not endian-safe.

**Comment by anoo1** [comment]
@williamli80 will take a look

**Comment by anoo1** [comment]
Fixed with https://github.com/openbmc/openpower-host-ipmi-oem/pull/13
